const items = [
    {
        id:'001',
        image:'men2.webp',
        company:'WROGN',
        item_name:'Men Cotton Green T-Shirt',
        current_price:606,
        original_price:1045,
        discount_percentage:42,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    {
        id:'002',
        image:'hero1.webp',
        company:'HERE&NOW ',
        item_name:'Men Cotton Black T-Shirt',
        current_price:443,
        original_price:899,
        discount_percentage:50,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    {
        id:'003',
        image:'offer3.webp',
        company:'Carlton London',
        item_name:'men t-shirt',
        current_price:606,
        original_price:1045,
        discount_percentage:42,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    {
        id:'004',
        image:'offer4.webp',
        company:'Carlton London',
        item_name:'men t-shirt',
        current_price:606,
        original_price:1045,
        discount_percentage:42,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    {
        id:'005',
        image:'offer5.jpg',
        company:'Carlton London',
        item_name:'men t-shirt',
        current_price:606,
        original_price:1045,
        discount_percentage:42,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    {
        id:'006',
        image:'offer6.webp',
        company:'Carlton London',
        item_name:'men t-shirt',
        current_price:606,
        original_price:1045,
        discount_percentage:42,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    {
        id:'007',
        image:'hero2.webp',
        company:'Roadster',
        item_name:'Men Cotton Dark , White T-Shirt',
        current_price:225,
        original_price:999,
        discount_percentage:77,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        }, 
    },
    {
        id:'008',
        image:'hero4.webp',
        company:'TRIPR ',
        item_name:'Men Cotton Blend T-Shirt',
        current_price:247,
        original_price:1999,
        discount_percentage:86,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        }, 
    },
    // {
    //     id:'009',
    //     image:'hero5.webp',
    //     company:'E-MAX ',
    //     item_name:'Men Polyester Grey T-Shirt',
    //     current_price:324,
    //     original_price:1299,
    //     discount_percentage:75,
    //     return_period:'14 Days return Available',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //         stars:4.5,
    //         count:1400,
    //     }, 
    // },
    // {
    //     id:'0010',
    //     image:'hero6.webp',
    //     company:'3BROS ',
    //     item_name:'Men Striped Cotton Orange T-Shirt',
    //     current_price:304,
    //     original_price:999,
    //     discount_percentage:69,
    //     return_period:'14 Days return Available',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //         stars:4.5,
    //         count:1400,
    //     }, 
    // },
    {
        id:'11',
        image:'campus1.webp',
        company:'CAMPUS',
        item_name:'ROYCE-2 Walking Shoes For Men  (Blue)',
        current_price:802,
        original_price:1099,
        discount_percentage:27,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        }, 
    },
    {
        id:'12',
        image:'nike1.webp',
        company:'NIKE',
        item_name:'REVOLUTION 7 WIDE Running Shoes For Men  (White)',
        current_price:2956,
        original_price:3695,
        discount_percentage:20,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        }, 
    },
    {
        id:'13',
        image:'hrx1.webp',
        company:'HRX by Hrithik Roshan ',
        item_name:'VELOCITY Running Shoes For Men  (blue)',
        current_price:1191,
        original_price:3999,
        discount_percentage:70,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        }, 
    },
    {
        id:'14',
        image:'puma4.webp',
        company:'PUMA',
        item_name:'Lazer Evo Casuals For Men ',
        current_price:837,
        original_price:3499,
        discount_percentage:76,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'15',
        image:'puma5.webp',
        company:'asian',
        item_name:'Nexon-13 White Sports,Wal',
        current_price:695,
        original_price:1199,
        discount_percentage:42,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'16',
        image:'puma6.webp',
        company:'PUMA',
        item_name:'Hampton Running Shoes For Men',
        current_price:1700,
        original_price:4999,
        discount_percentage:62,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'17',
        image:'puma7.webp',
        company:'PUMA',
        item_name:'Cricket Power Cricket Shoes For Men',
        current_price:1879,
        original_price:4999,
        discount_percentage:62,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'18',
        image:'hrx2.webp',
        company:'HRX by Hrithik Roshan ',
        item_name:'SWIFT RUN Running Shoes For Men  (Navy)',
        current_price:924,
        original_price:3299,
        discount_percentage:71,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    // {
    //     id:'19',
    //     image:'campus2.webp',
    //     company:'CAMPUS',
    //     item_name:'CAMP KARL Running Shoes For Men  (White)',
    //     current_price:987,
    //     original_price:1299,
    //     discount_percentage:24,
    //     return_period:'14 Days return Available',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //         stars:4.5,
    //         count:1400,
    //     },  
    // },
    // {
    //     id:'20',
    //     image:'puma10.webp',
    //     company:'PUMA',
    //     item_name:'Smash V2 Buck Sneakers For Men',
    //     current_price:1511,
    //     original_price:4999,
    //     discount_percentage:66,
    //     return_period:'14 Days return Available',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //         stars:4.5,
    //         count:1400,
    //     },  
    // },
    {
        id:'21',
        image:'l1.webp',
        company:'spera ',
        item_name:'Women Printed Viscose Rayon Straight Kurta  (Green)',
        current_price:638,
        original_price:2044,
        discount_percentage:68,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'22',
        image:'l2.webp',
        company:'EthnicBasket ',
        item_name:'Women Floral Print Crepe Straight Kurta  (Brown)',
        current_price:194,
        original_price:799,
        discount_percentage:81,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'23',
        image:'l3.webp',
        company:'KIRTI ',
        item_name:'Women Printed Pure Cotton Straight Kurta  (White)',
        current_price:255,
        original_price:1298,
        discount_percentage:66,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'24',
        image:'l4.webp',
        company:'EthnicBasket ',
        item_name:'Women Printed Crepe Straight Kurta  (Red)',
        current_price:194,
        original_price:999,
        discount_percentage:85,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'25',
        image:'l5.webp',
        company:'SEAKART ',
        item_name:'Women Embroidered Pure Cotton Straight Kurta  (Yellow, White)',
        current_price:354,
        original_price:2499,
        discount_percentage:85,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'26',
        image:'l6.webp',
        company:'DSK STUDIO ',
        item_name:'Women Printed Crepe Straight Kurta  (Dark Green)',
        current_price:194,
        original_price:749,
        discount_percentage:80,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'27',
        image:'l7.webp',
        company:'anushansa ',
        item_name:'Women Floral Print Viscose Rayon Anarkali Kurta  (Black, Pink, Yellow)',
        current_price:314,
        original_price:999,
        discount_percentage:68,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    {
        id:'28',
        image:'l8.webp',
        company:'DADIYA ',
        item_name:'Women Paisley Viscose Rayon Anarkali Kurta  (Purple)',
        current_price:344,
        original_price:1599,
        discount_percentage:78,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },  
    },
    // {
    //     id:'29',
    //     image:'l9.webp',
    //     company:'JaishreeFab ',
    //     item_name:'Women Printed Viscose Rayon Ethnic Dress  (Pink)',
    //     current_price:320,
    //     original_price:1999,
    //     discount_percentage:83,
    //     return_period:'14 Days return Available',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //         stars:4.5,
    //         count:1400,
    //     },  
    // },
    // {
    //     id:'30',
    //     image:'l10.webp',
    //     company:'JAFFRY EMBROIDERY ',
    //     item_name:'Women Printed Viscose Rayon Anarkali Kurta  (Blue)',
    //     current_price:394,
    //     original_price:1299,
    //     discount_percentage:69,
    //     return_period:'14 Days return Available',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //         stars:4.5,
    //         count:1400,
    //     },  
    // },
    {
        id:'31',
        image:'watch1.webp',
        company:'PETER ENGLAND ',
        item_name:'Analog Watch - For Men PE000017D',
        current_price:1284,
        original_price:2595,
        discount_percentage:50,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    {
        id:'32',
        image:'watch2.webp',
        company:'A/X ARMANI EXCHANGE',
        item_name:'Hampton Analog Watch - For Men AX2122',
        current_price:6998,
        original_price:17495,
        discount_percentage:60,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'33',
        image:'watch3.webp',
        company:'PETER ENGLAND ',
        item_name:'Analog Watch - For Men PE000025A',
        current_price:1074,
        original_price:2899,
        discount_percentage:62,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'34',
        image:'watch4.webp',
        company:'FOSSIL ',
        item_name:'RHETT Analog Watch - For Men BQ1009',
        current_price:4998,
        original_price:12495,
        discount_percentage:60,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'35',
        image:'watch5.webp',
        company:'Titan',
        item_name:'Karishma Analog Watch - For Men NN1639SM01',
        current_price:1436,
        original_price:1995,
        discount_percentage:28,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'36',
        image:'watch6.webp',
        company:'CASIO',
        item_name:'Enticer Men MTP-1314D-2AVDF  Analog Watch For Men A551',
        current_price:2376,
        original_price:3395,
        discount_percentage:30,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'37',
        image:'watch7.webp',
        company:'Fastrack',
        item_name:'Wear your look Analog Watch - For Men 3089NM03',
        current_price:2236,
        original_price:2795,
        discount_percentage:20,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'38',
        image:'watch8.webp',
        company:'Espoir',
        item_name:'Analog Watch - For Men ES2616',
        current_price:319,
        original_price:2495,
        discount_percentage:87,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'39',
        image:'living9.webp',
        company:'ONLINECRAFTS',
        item_name:'Wooden wall mount plus shape Floating rack',
        current_price:351,
        original_price:1999,
        discount_percentage:82,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'40',
        image:'living10.webp',
        company:'TheNextStore',
        item_name:'Zigzag Corner Wall Mount Shelf Unit/Racks and Shelves',
        current_price:2192,
        original_price:3030,
        discount_percentage:27,
        return_period:'14 Days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'41',
        image:'living1.webp',
        company:'GULLAK Mac 36 ',
        item_name:'27 inch X 30 inch, White',
        current_price:128,
        original_price:1299,
        discount_percentage:90,
        return_period:'14 days return Available',
        delivery_date:'10 Oct 2024',
        rating:{
            stars:4.5,
            count:1400,
        },

    },
    {
        id:'42',
        image:'living2.webp',
        company:'WOODENXDECOR',
        item_name:'Floating Shelves for Wall Set',
        current_price:559,
        original_price:1499,
        discount_percentage:60,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'43',
        image:'living3.webp',
        company:'stardecor',
        item_name:'Book Rack for Study Room, Office',
        current_price:580,
        original_price:1299,
        discount_percentage:55,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'44',
        image:'living4.webp',
        company:' SHAPE BROWN MDF',
        item_name:'Medium Density Fiber',
        current_price:295,
        original_price:1099,
        discount_percentage:73,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'45',
        image:'living5.webp',
        company:'PINECREW ',
        item_name:'Multipurpose Wall Mount Self',
        current_price:195,
        original_price:999,
        discount_percentage:95,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'46',
        image:'living6.webp',
        company:'Captiver ',
        item_name:'Aai Set Top Box Stand',
        current_price:559,
        original_price:1199,
        discount_percentage:36,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'47',
        image:'living7.webp',
        company:'ONLINECRAFTS ',
        item_name:'Wooden wall mount plus shape Floating rack',
        current_price:856,
        original_price:1999,
        discount_percentage:57,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'48',
        image:'living8.webp',
        company:'JANAKI SHOP ',
        item_name:'Home Wall Decor Wooden Wall Shelf ',
        current_price:225,
        original_price:889,
        discount_percentage:74,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'49',
        image:'living10.webp',
        company:'TheNextStore',
        item_name:'Zigzag Corner Wall Mount Shelf Unit/Racks and Shelves',
        current_price:680,
        original_price:3104,
        discount_percentage:78,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'50',
        image:'living9.webp',
        company:'ONLINECRAFTS ',
        item_name:'Wooden wall mount plus shape Floating rack ',
        current_price:856,
        original_price:1999,
        discount_percentage:57,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'51',
        image:'boat1.webp',
        company:'boAt Airdopes',
        item_name:' Bluetooth Headset  (Cool Sapphire,',
        current_price:899,
        original_price:2490,
        discount_percentage:63,
        return_period:'14 daya return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'52',
        image:'boat2.webp',
        company:'Blaupunkt',
        item_name:'BTW09 AIR BK Bluetooth Headset',
        current_price:999,
        original_price:3499,
        discount_percentage:71,
        return_period:'14 daya return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'53',
        image:'boat3.webp',
        company:'realme Buds Wireless 2 Neo',
        item_name:'with Type-C Fast Charge & Bass Boost+ Bluetooth Headset',
        current_price:1299,
        original_price:2499,
        discount_percentage:48,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'54',
        image:'boat4.webp',
        company:'realme Techlife Buds T100',
        item_name:'with up to 28 Hours Playback Calls Bluetooth Headset',
        current_price:1349,
        original_price:2999,
        discount_percentage:55,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'55',
        image:'boat5.webp',
        company:'OnePlus Bullets Wireless Z2 ',
        item_name:'Bluetooth Headset  Bluetooth Headset  ',
        current_price:1499,
        original_price:2299,
        discount_percentage:34,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'56',
        image:'boat6.webp',
        company:'OnePlus Nord Buds 2r',
        item_name:'Wireless in Ear Clear Call Bluetooth Headset ',
        current_price:1999,
        original_price:2299,
        discount_percentage:13,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'57',
        image:'boat7.webp',
        company:'CARRON ',
        item_name:' 48 Hour Playtime  Bluetooth Headset  ',
        current_price:411,
        original_price:1999,
        discount_percentage:79,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    },
    {
        id:'58',
        image:'boat8.webp',
        company:'Boult ProBass ',
        item_name:'ZEN Mode ENC, 32hrs Bluetooth Headset',
        current_price:699,
        original_price:4499,
        discount_percentage:84,
        return_period:'14 days return Availabel',
        delivery_date:'10 Oct 2024',
        rating:{
        stars:4.5,
        count:1400,
        },
    }
    // {
    //     id:'59',
    //     image:'boat9.webp',
    //     company:'OnePlus Bullets Wireless',
    //     item_name:'Bluetooth Headset ',
    //     current_price:1499,
    //     original_price:2299,
    //     discount_percentage:34,
    //     return_period:'14 days return Availabel',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //     stars:4.5,
    //     count:1400,
    //     },
    // },
    // {
    //     id:'60',
    //     image:'boat10.webp',
    //     company:'Aroma NB119',
    //     item_name:'60 Hours Playtime Fast Bluetooth Headset  ',
    //     current_price:402,
    //     original_price:2999,
    //     discount_percentage:86,
    //     return_period:'14 days return Availabel',
    //     delivery_date:'10 Oct 2024',
    //     rating:{
    //     stars:4.5,
    //     count:1400,
    //     },
    // }


];